[build]
  command = "npm install && npm run build"
  functions = "functions"

[[redirects]]
  from = "/api/p2/*"
  to = "/.netlify/functions/server/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/api/p1"
  to = "https://mediacatalog.netlify.app/.netlify/functions/server/another"
  status = 200
  force = true