# This is a basic workflow to help you get started with Actions

name: curl1

# Controls when the action will run. 
on:
  push:
  schedule:
    - cron: '*/30 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Hit HD_HU
      uses: wei/curl@v1
      with:
        args: -X POST ${{secrets.CURL_HD_HU_WITH_CRED}} -d ''
    - name: Hit EX_MO
      uses: wei/curl@v1
      with:
        args: -X POST ${{secrets.CURL_EX_MO_WITH_CRED}} -d ''
